### ISSUE TITLE
[feat] add issue and PR template

### ISSUE THREAD

**Issue by kr-anurag** [kr-anurag/formie#47]

**Comment by kr-anurag** [comment]
note: move the templates to the .github directory, keep it simple, and basically you can copy-paste from this

[Issue and PR Tmeplates](https://github.com/kr-anurag/dscan/tree/main/.github)

**Comment by avneesh0612** [comment]
Can I take this?

**Comment by kr-anurag** [comment]
> Can I take this?

sure! go ahead! thanks

**Comment by avneesh0612** [comment]
This issue can be closed now...
